### ISSUE TITLE
frontend ideas

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#190]

**Comment by xavierlave1** [comment]
**Feedback session observations/suggestions, with Antje and Ken :**

The frontend is looking great, and most of the functionalities are already here so we are very excited for the future !! 👍 

Observations :

- [ ] When logged in as **_demo_**, we can create a project with only **_admin_** as a user, yet we can work on it

- [ ] Some users should be in 'View only', or be allowed to play around with the project without the authorisation to save anything. Maybe a temporary database for these users ?
- [ ] Instead of having the _**save**_ button near the parameters sliders, should we have a compute-on-release mode ? So that it requires one less click, without being as computationally expensive as a 'continuous' simulation
- [ ] Unit display of the model is not exactly clear<img width="384" alt="Screenshot 2021-09-29 at 13 13 13" src="https://user-images.githubusercontent.com/72130923/135257694-9c8a3146-2197-4008-bc50-c2722cb71207.png">
- [ ] The graph should stay in place as we scroll down to lower parameters
- [ ] Users should be able to choose color/shape data stratification depending on any column they want (Dose group, strain,...), similar to Spotfire
- [ ] In the simulation graph, allow users to zoom on the y-axis, not only x-axis. Also, in case the user wants to export/screenshot the graph, he should be able to choose the scale of the x- and y-axis
- [ ] In the time units, **_hours_** and _**h**_ are two different things (yet they are equivalent in the simulation)
- [ ] In the **_Components_** dropdown, the choice should be more precise than **_Myokit_** (maybe we could even get rid of that dropdown ?)
- [ ] In the **_Components_** dropdown, we could have different **_Variables_**, **_Initial Conditions_**, **_Outputs_** tabs, so that it is easier to see what we are doing
- [ ] **_Modeling_** tab could be renamed **_Simulation_**
- [ ] The **_Projects_**, **_Modeling(Simulation)_**, **_Data Analysis_**, **_Inference_** could be moved to the top so the left tabs are less crowded, and so we can easily understand the steps to follow in order to infer the parameters
- [ ] When creating a new model, it should be selected directly, or it is easy to get lost, or think it was not created
- [ ] PK model initial condition should be 0 by default
- [ ] The different compartments of a model should have their sliders in the same area, or it gets messy to play around
- [ ] When creating a new protocol, we cannot directly use it in a PK model, we need to refresh to do so

Sorry there are a lot of things and not really split into categories, but here are all things we saw while doing a tour of the app on heroku ! Tell me if some points are not clear, I wrote them on-the-go so there probably are imperfections

**Comment by martinjrobins** [comment]
Thanks @xavierlave1, these are very useful. I've got a few questions, but we can go through these at the next meeting

**Comment by martinjrobins** [comment]
- font size on chart is smaller than the rest

**Comment by martinjrobins** [comment]
closing as this was for the older version
