### ISSUE TITLE
Check out TimeSeries database 

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#26]
Relates to #25 

See https://www.influxdata.com/.

**Comment by martinjrobins** [comment]
here is a SO showing how to get influx and django working together: https://stackoverflow.com/questions/50198741/django-influxdb

**Comment by martinjrobins** [comment]
So my feeling is that a timeseries database is overkill as we don't need the defining feature, which is continual updating of data (mainly used for IOTs). 

I think we should go for an object store for data, in a csv format. Rather than use the filesystem to store these, we should use a data "bucket". Basically you just throw all the data files into this bucket, and get a unique id to identify and retrieve/update them. I've used minio object store once before (very briefly), and it seems pretty good: https://min.io/
